### ISSUE TITLE
User-feedback style

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#100]
Comment from a prospective "user"...  I tried to explain this myself ages ago and the exception text was indeed made "less alarming" to Joe Muppet.  Not sure how to make it any more friendly, but included the original comment here in case you have any thoughts...

Can’t really explain it, but when there is a button in the app I think that better give the feeling that “this is working as it should, there is an error here, but it is for a specific reason, there isn’t anything wrong with the app, it is you.”

**Comment by pjfl** [comment]
It already does this. The are growler like notitifications in the bottom right corner which let you know when an action was performed successfully. The error messages let you know when something has gone wrong (but not what went wrong since the messages were dumbed down). I have created a wiki entry for this kind of vague, https://github.com/pjfl/p5-app-notitia/wiki/User-Requests-and-Ideas
