### ISSUE TITLE
Disallow more than "N" consecutive slots

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#128]
You should not be able to claim more than N (configurable value, defaulting to 3) consecutive duties. There should, however, be an "override" to allow "rota manager" to allow an individual to do so. This might be just the rota-manager role can assign a slot to someone regardless.

**Comment by pjfl** [comment]
Do you mean consecutive slots? No more than n day *or* night shifts, or no more than n day *and* night shifts?

**Comment by JB62** [comment]
No more than n consecutive slots..


If N were 3, you can do Wednesday night, Thursday night, Friday night but you can't then do Saturday day.  If you did Friday night, Saturday day and Saturday night, you can't do Sunday day...



⁣​

**Comment by pjfl** [comment]
The bank holiday issue will stuff this up. If I code this then you will also need an admin screen where you must enter the bank holiday dates so that the logic can correctly account for the day shift on a bank holiday. If you don't enter the bank holidays then someone would be prevented from doing Sun. night, bank holiday Mon. day, Mon. night, Tues. night. (I think)

Also in the second example above your saying it's ok for someone to do a 36hr shift. Is that intentional?

Also there is nothing consecutive about the slots in the above examples. Those weekday day shifts are still there, we're just ignoring them apart from bank holidays when we do want to include them in any contiguous slot counting

**Comment by JB62** [comment]
They are consecutive, but i know it's slightly arbitrary. perhaps consign this to the "too much ⁣​of a pain in the arse" bucket.

**Comment by pjfl** [comment]
At v0.10.25 we now know when the bank holidays are

**Comment by pjfl** [comment]
Can you check the logic in [this](https://github.com/pjfl/p5-app-notitia/blob/master/lib/App/Notitia/Schema/Schedule/Result/Person.pm#L202) subroutine to make sure it's what you wanted?

**Comment by JB62** [comment]
I don't think you need to set worry about the slot type, just N consecutive duties - doesn't matter if they are as a rider driver or controller.

The point is really duty of care - if someone has been out all night or on the phone all night for three duties, they will potentially be unsafe on the road or at work by the fourth duty. We do need the rule to be overridden though - perhaps no call out for two days say, so perhaps don't apply the rule if booking a slot within M days of 'now' ?

**Comment by JB62** [comment]
It seems we want to change the criteria here such that "no one can do more than three blocks of 24 hours (or part of) in a row."

    Friday night, Saturday day and night, Sunday day and night is okay
    Wed night, Thur night, Friday night is okay
    Thur night, Friday night, Saturday day and night, Sunday day and night is not
    Friday night, Saturday day and night, Sunday day and night, Monday night is not
    Wed night, Thur night, Friday night is okay, Saturday day is not

...etc

I think this means _assert_not_too_many_slots just has to check for an "empty" day between two days before and two days following the prospective date

**Comment by JB62** [comment]
Will this do the job here do you think?

[patch.txt](https://github.com/pjfl/p5-app-notitia/files/691084/patch.txt)

**Comment by JB62** [comment]
https://github.com/pjfl/p5-app-notitia/pull/148
