### ISSUE TITLE
No need for the "R" column in the spreadsheet view

### ISSUE THREAD

**Issue by JB62** [pjfl/p5-app-notitia#64]
Not needed

**Comment by pjfl** [comment]
In which case it's not needed at all. You want it removed?

**Comment by JB62** [comment]
It is "vehicle requested" yes? In which case, we agreed the presence of the vehicle drop down showed there was a request didn't we?

**Comment by pjfl** [comment]
No. The region code (N, C, or S) appears regardless of whether a vehicle was requested or not. It only appears on the spreadsheet view because it was in the png that I received as a spec. It serves no programmatic purpose and since we have both location and outer postcode on the same screen I think we can do without it if Guy agrees

**Comment by JB62** [comment]
Sorry - my mistake - leave it there for now. Sorry chap.

**Comment by pjfl** [comment]
Had a thought. If you don't mind the region being defined by a straight horizontal line on the map I could use the y coordinate to populate the region field. It would be a config option containing two ints. If someones  y coord is less than both ints then their region is S, between the two ints is C, greater than the two ints is N. Would save you having to maintain the region field by hand. Only works if it's ok to define the regions using a straight line

**Comment by JB62** [comment]
Doesn't need to be a horizontal line - simple formula we can define in the config?  Keep it in mind, but leave manually defined regions for now i think.

**Comment by pjfl** [comment]
Since #61 is now implemented we are now using the region code to limit slot claims so I'm closing this issue. If you want to produce the two lists of ints that would split OBN into three regions then open another issue and I'll implement the auto population of the region field based on a rider coordinates
